---
abstract: Perl GUI Test Utilities.
author:
  - 'Dennis K. Paulsen (ctrondlp@cpan.org), Ernesto Guisado (erngui@acm.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-GuiTest
no_index:
  directory:
    - t
    - inc
    - eg
    - Recorder
  file:
    - Makefile.PL
    - makedist.pl
requires: {}
resources:
  repository: http://github.com/dk/Win32-GuiTest
version: 1.60
