--- #YAML:1.0
name:               Win32-GuiTest
version:            1.58
abstract:           Perl GUI Test Utilities.
author:
    - Dennis K. Paulsen (ctrondlp@cpan.org), Ernesto Guisado (erngui@acm.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
